SET client_encoding = 'UTF8';

-- On efface toutes les donnees de la table famille_plante
delete from famille_plante;

-- On remet le compteur de séquence à redémarrer à 1
alter SEQUENCE famille_plante_fap_id_seq RESTART WITH 1;

-- On insere les donnees de semencier
insert into famille_plante (fap_nom) values 
('Ail'),
('Artichauts'),
('Aubergines'),
('Betteraves rouges'),
('Bettes à tondre'),
('Brocolis'),
('Cardons'),
('Carottes'),
('Celeri-raves'),
('Celeris branche'),
('Chicorées endive'),
('Chicorées frisées'),
('Chicorées pain de sucre'),
('Chicorées sauvages'),
('Chicorées scaroles'),
('Chicorées très fines maraîchères'),
('Chou-fleur'),
('Choux de bruxelles'),
('Choux de chine'),
('Choux pommées blancs'),
('Choux pommées rouges'),
('Choux-raves'),
('Concombres'),
('Cornichons'),
('Côtes de bette'),
('Courges'),
('Courgettes'),
('Cresson alenois'),
('Echalotes'),
('Engrais vert'),
('Epinards'),
('Fenouils'),
('Fèves'),
('Haricots à rames'),
('Haricots nains'),
('Laitues à couper'),
('Laitues batavias de pleine terre'),
('Laitues batavias et feuilles de chêne d''abris'),
('Laitues batavias icebergs'),
('Laitues d''abris'),
('Laitues grasses'),
('Laitues pommées de pleine terre'),
('Laitues romaines'),
('Mâches'),
('Mais doux'),
('Melons'),
('Navets'),
('Oignons bulbilles'),
('Oignons'),
('Panais'),
('Pastèques'),
('Patissons'),
('Poireaux'),
('Pois nain, demi-rame et mangetout'),
('Poivrons'),
('Pommes de terre'),
('Radis'),
('Semences condimentaires'),
('Semences florales'),
('Tomates');

